level = info

writer = rolling file
writer.file = ${user.home}/.local/share/api-x/logs/{date: yyyy-MM-dd}/api-x_{count}.log
writer.policies = startup, daily
writer.format = {date: HH:mm:ss.SSS} [{level}] ({file}:{line}) {message}
